services:
  rss-bot:
    container_name: rss-bot
    image: rss-bot
    build: .
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    command: ["python", "bot.py"]
